import asyncio
import aiohttp
import json
import ssl
import certifi


class HideMyEmail:
    base_url_v1 = "https://p68-maildomainws.icloud.com/v1/hme"
    base_url_v2 = "https://p68-maildomainws.icloud.com/v2/hme"
    params = {
        "clientBuildNumber": "2536Project32",
        "clientMasteringNumber": "2536B20",
        "clientId": "",
        "dsid": "", # Directory Services Identifier (DSID) is a method of identifying AppleID accounts
    }

    def __init__(self, label: str = "rtuna's gen", cookies: str = ""):
        """Initializes the HideMyEmail class.

        Args:
            label (str)     Label that will be set for all emails generated, defaults to `rtuna's gen`
            cookies (str)   Cookie string to be used with requests. Required for authorization.
        """
        # Label that will be set for all emails generated, defaults to `rtuna's gen`
        self.label = label

        # Cookie string to be used with requests. Required for authorization.
        self.cookies = cookies

    async def __aenter__(self):
        connector = aiohttp.TCPConnector(ssl_context=ssl.create_default_context(cafile=certifi.where())) 
        self.s = aiohttp.ClientSession(
            headers={
                "Connection": "keep-alive",
                "Pragma": "no-cache",
                "Cache-Control": "no-cache",
                "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36",
                "Content-Type": "text/plain",
                "Accept": "*/*",
                "Sec-GPC": "1",
                "Origin": "https://www.icloud.com",
                "Sec-Fetch-Site": "same-site",
                "Sec-Fetch-Mode": "cors",
                "Sec-Fetch-Dest": "empty",
                "Referer": "https://www.icloud.com/",
                "Accept-Language": "en-US,en-GB;q=0.9,en;q=0.8,cs;q=0.7",
                "sec-ch-ua": '"Brave";v="141", "Not?A_Brand";v="8", "Chromium";v="141"',
                "sec-ch-ua-mobile": "?0",
                "sec-ch-ua-platform": '"macOS"',
                "Cookie": self.__cookies.strip(),
            },
            timeout=aiohttp.ClientTimeout(total=10),
            connector=connector,
        )

        return self

    async def __aexit__(self, exc_t, exc_v, exc_tb):
        await self.s.close()

    @property
    def cookies(self) -> str:
        return self.__cookies

    @cookies.setter
    def cookies(self, cookies: str):
        # remove new lines/whitespace for security reasons
        self.__cookies = cookies.strip()

    async def _request_json(self, method: str, url: str, **kwargs) -> dict:
        try:
            async with self.s.request(method, url, **kwargs) as resp:
                if resp.status == 429:
                    return {"error": 1, "reason": "Apple rate limit reached (HTTP 429)"}

                body = await resp.text()
                if not body.strip():
                    return {
                        "error": 1,
                        "reason": f"Invalid Apple response (HTTP {resp.status}: empty body)",
                    }

                try:
                    return json.loads(body)
                except json.JSONDecodeError:
                    return {
                        "error": 1,
                        "reason": (
                            "Invalid Apple response "
                            f"(HTTP {resp.status}: expected JSON body)"
                        ),
                    }
        except asyncio.TimeoutError:
            return {"error": 1, "reason": "Request timed out"}
        except aiohttp.ClientError as e:
            return {"error": 1, "reason": f"Network error: {e}"}
        except Exception as e:
            return {"error": 1, "reason": str(e)}

    async def generate_email(self) -> dict:
        """Generates an email"""
        return await self._request_json(
            "POST",
            f"{self.base_url_v1}/generate",
            params=self.params,
            json={"langCode": "en-us"},
        )

    async def reserve_email(self, email: str) -> dict:
        """Reserves an email and registers it for forwarding"""
        payload = {
            "hme": email,
            "label": self.label,
            "note": "Generated by rtuna's iCloud email generator",
        }
        return await self._request_json(
            "POST",
            f"{self.base_url_v1}/reserve",
            params=self.params,
            json=payload,
        )

    async def list_email(self) -> dict:
        """List all HME"""
        return await self._request_json(
            "GET",
            f"{self.base_url_v2}/list",
            params=self.params,
        )
